VCompany/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^storage/', include('VStorage.urls'))
]

VStorage/urls.py
from django.conf.urls import url

from . import views

app_name = 'store'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^clients/$', views.clients, name='clients'),
    url(r'^products/$', views.products, name='products'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^addproduct/$', views.add_product, name='add_product'),
    url(r'^addajax/$', views.ajax_add_product, name='ajax_add_product'),
    url(r'^changeajax/$', views.ajax_change_product, name='ajax_change_product'),
    url(r'^neworder/$', views.new_order, name='new_order'),
    url(r'^basketajax/$', views.ajax_add_basket, name='ajax_add_basket'),
    url(r'^basket/$', views.basket, name='basket'),
    url(r'^basketclient/$', views.next_basket, name='next_basket'),
    url(r'^result/$', views.result, name='result'),
    url(r'^endresult/$', views.endresult, name='res_end'),
]

VStorage/models.py
from django.db import models
from django.contrib.auth.models import User


class Client(models.Model):
    client_id = models.AutoField(primary_key=True)
    client_name = models.CharField(max_length=50, null=True, default=None)
    client_passport = models.CharField(max_length=11, null=True, default=None)
    client_birthday = models.DateField(blank=True, null=True, default=None)

    class Meta:
        db_table = 'Client'


class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=50)
    product_cost = models.FloatField()
    product_made = models.CharField(max_length=20)
    product_category = models.CharField(max_length=50)

    class Meta:
        db_table = 'Product'


class Branch(models.Model):
    branch_id = models.AutoField(primary_key=True)
    branch_address = models.CharField(max_length=100)

    class Meta:
        db_table = 'Branch'


class Manager(models.Model):
    manager_id = models.AutoField(primary_key=True)
    manager_name = models.CharField(max_length=50)
    manager_birthday = models.DateField()
    manager_recruitment = models.DateField()
    manager_salary = models.IntegerField()
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    user = models.OneToOneField(User, default=None)

    class Meta:
        db_table = 'Manager'


class Auto(models.Model):
    auto_id = models.AutoField(primary_key=True)
    auto_model = models.CharField(max_length=50)
    auto_number = models.CharField(max_length=12)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Auto'


class Driver(models.Model):
    driver_id = models.AutoField(primary_key=True)
    driver_name = models.CharField(max_length=50)
    driver_birthday = models.DateField()
    driver_salary = models.IntegerField()
    driver_recruitment = models.DateField()
    auto = models.ForeignKey(Auto, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Driver'


class Ordertable(models.Model):
    order_id = models.AutoField(primary_key=True)
    order_date = models.DateField()
    order_address = models.CharField(max_length=100, null=True, default=None)
    order_totalcost = models.FloatField()
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, null=True, default=None)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    auto = models.ForeignKey(
        Auto, on_delete=models.CASCADE, null=True, default=None)

    class Meta:
        db_table = 'OrderTable'


class Branchproduct(models.Model):
    branchproduct_id = models.AutoField(primary_key=True)
    product_rest = models.IntegerField()
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        db_table = 'BranchProduct'


class Orderproduct(models.Model):
    orderproduct_id = models.AutoField(primary_key=True)
    product_count = models.IntegerField()
    order = models.ForeignKey(Ordertable, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        db_table = 'OrderProduct'

VStorage/forms.py
from django import forms
from .models import Product


class AddProduct(forms.ModelForm):
    product_count = forms.IntegerField()

    class Meta:
        model = Product
        fields = ['product_name', 'product_category',
                  'product_made', 'product_cost']

VStorage/views.py
from django.http import HttpResponse
from .models import *
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from .forms import *
from django.db import connection
import json
import datetime


@login_required
def index(request):
    context = {}
    return render(request, 'VStorage/index.html', context)


@login_required
def clients(request):
    context = {
        'clients_list': Client.objects.raw("select * from Client"),
    }
    return render(request, 'VStorage/clients.html', context)


@login_required
def products(request):
    context = {}
    if request.POST:
        rest = {
            "absence": "danger",
            "middle": "",
            "many": "success"
        }
        branch = request.session['branch_id']
        context['products_list'] = Product.objects.raw(
            "call products_in_branch(%s)", [branch])
        context['color'] = rest
        return render(request, 'VStorage/products.html', context)
    return render(request, 'VStorage/products.html', context)


@login_required
def add_product(request):
    context = {}
    return render(request, 'VStorage/add_product.html', context)


@login_required
def ajax_add_product(request):
    form = AddProduct(request.POST)
    if request.is_ajax():
        if form.is_valid():
            product_name = form.cleaned_data.get('product_name')
            product_category = form.cleaned_data.get('product_category')
            product_made = form.cleaned_data.get('product_made')
            product_cost = form.cleaned_data.get('product_cost')
            product_count = form.cleaned_data.get('product_count')
            search = Product.objects.filter(product_name=product_name,
                                            product_category=product_category,
                                            product_made=product_made)
            if search:
                content = json.dumps({'product_name': product_name,
                                      'product_category': product_category,
                                      'product_made': product_made,
                                      'product_cost': product_cost,
                                      'product_count': product_count})
                return HttpResponse(content, content_type='application/json')
            else:
                cursor = connection.cursor()
                cursor.execute(
                    "call add_product(%s,%s,%s,%s,%s,%s)",
                    [product_name, product_category, product_made,
                     product_cost, product_count,
                     request.session['branch_id']])
                cursor.close()
                return HttpResponse("Товар добавлен")
        else:
            return HttpResponse()
    return HttpResponse()


@login_required
def ajax_change_product(request):
    if request.is_ajax():
        product_name = request.POST.get('product_name')
        product_category = request.POST.get('product_category')
        product_made = request.POST.get('product_made')
        product_cost = request.POST.get('product_cost')
        product_count = request.POST.get('product_count')
        cursor = connection.cursor()
        cursor.execute(
            "call change_product(%s,%s,%s,%s,%s,%s)",
            [product_name, product_category, product_made,
             product_cost, product_count, request.session['branch_id']])
        cursor.close()
    return HttpResponse()


@login_required
def new_order(request):
    context = {}
    if request.POST:
        if request.POST.getlist('product_count_b'):
            sess = request.session['basket']
            my_list = request.POST.getlist('product_count_b')
            for i in range(len(sess)):
                sess[i][5] = my_list[i]
            # print(sess)
            request.session['basket'] = sess
        # сессия хранит список выбранных объектов
        # каждый элемент списка - список с данными о продукте
        branch = request.session['branch_id']
        context['order_products_list'] = Product.objects.raw(
            "call products_in_branch(%s)", [branch])
        context['products_count'] = len(request.session['basket'])
        return render(request, 'VStorage/new_order.html', context)
    return render(request, 'VStorage/new_order.html', context)


@login_required
def ajax_add_basket(request):
    if request.is_ajax():
        # print(request.POST)
        product_id = request.POST.get('product_id')
        product_name = request.POST.get('product_name')
        product_category = request.POST.get('product_category')
        product_made = request.POST.get('product_made')
        product_cost = request.POST.get('product_cost')
        # product_count = request.POST.get('product_count')
        sess = request.session['basket']
        product_info = [product_id, product_name,
                        product_category, product_made,
                        product_cost, 1]
        sess.append(product_info)
        request.session['basket'] = sess
        content = json.dumps(request.session['basket'])
        return HttpResponse(content, content_type='application/json')
    return HttpResponse()


@login_required
def basket(request):
    context = {}
    return render(request, "VStorage/basket.html", context)


@login_required
def next_basket(request):
    if request.POST:
        if request.POST.getlist('product_count_b'):
            sess = request.session['basket']
            my_list = request.POST.getlist('product_count_b')
            for i in range(len(sess)):
                sess[i][5] = my_list[i]
            # print(sess)
            request.session['basket'] = sess
    return render(request, "VStorage/next_basket.html", {})


@login_required
def result(request):
    context = {}
    if request.POST:
        context['client_name'] = request.POST['client_name']
        request.session['client_name'] = request.POST['client_name']
        context['client_address'] = request.POST['address']
        request.session['client_address'] = request.POST['address']
        context['client_birthday'] = request.POST['client_birthday']
        request.session['client_birthday'] = request.POST['client_birthday']
        totalcost = 0
        for i in range(len(request.session['basket'])):
            totalcost += (int(request.session['basket'][i][4]) *
                          int(request.session['basket'][i][5]))
        # print(request.session['basket'])
        context['cost'] = totalcost
        request.session['cost'] = totalcost
        return render(request, 'VStorage/result.html', context)
    return render(request, 'VStorage/result.html', context)


@login_required
def endresult(request):
    if request.POST:
        cursor = connection.cursor()
        print(datetime.date.today)
        cursor.execute(
            "call make_order(%s,%s,%s,%s,%s,%s,%s)",
            [request.session['man_id'], request.session['branch_id'],
             request.session['client_name'],
             request.session['client_address'], request.session[
                'client_birthday'],
             request.session['cost'], datetime.date.today()])
        sess = request.session['basket']
        for i in range(len(sess)):
            cursor.execute("""
                call order_product(%s,%s)""", [sess[i][0], sess[i][5]])
        cursor.close()
        del request.session['basket']
        del request.session['client_name']
        del request.session['client_address']
        del request.session['client_birthday']
        del request.session['cost']
        request.session['basket'] = []
        context = {}
        return render(request, 'VStorage/index.html', context)


def login(request):
    auth.logout(request)
    context = {}
    # request.session['branch_id'] = None
    # request.session['branch_address'] = None
    # request.session['basket'] = None
    request.session['basket'] = []
    if request.POST:
        name = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=name, password=password)
        if user is not None:
            if user.username == 'admin':
                return redirect('/admin/')
            elif user.username != 'admin':
                man_dict = {
                    'man_id': Manager.objects.raw("""
                    call get_manager(%s)""", [user.username])
                }
                branch_dict = {
                    'branch': Branch.objects.raw(
                        "call get_branch(%s)", [user])
                }
                request.session['man_id'] = man_dict['man_id'][0].manager_id
                request.session['branch_id'] = branch_dict[
                    'branch'][0].branch_id
                request.session['branch_address'] = branch_dict[
                    'branch'][0].branch_address
                auth.login(request, user)
                return redirect('/storage/')
        else:
            context = {
                'error': "Неверный логин или пароль",
            }
            return render(request, 'VStorage/login.html', context)
    return render(request, 'VStorage/login.html', context)


def logout(request):
    del request.session['branch_id']
    del request.session['branch_address']
    del request.session['basket']
    del request.session['man_id']
    auth.logout(request)
    return redirect('/storage/')

VStorage/templates/VStorage/add_product.html
{% extends 'VStorage/base.html' %}
{% block content %}
{% if user.is_authenticated %}
{% include 'VStorage/script.html' %}
<div class="col-md-10 col-md-offset-1">
    <div class="table-responsive">
        <table class="table table-bordered">
            <caption id="caption_table">
                <h2>Добавление товара</h2></caption>
            <thead>
                <tr>
                    <th>Наименование</th>
                    <th>Категория</th>
                    <th>Страна изготовитель</th>
                    <th>Цена</th>
                    <th>Количество</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="col-md-2">
                        <input id="id_product_name" maxlength="50" name="product_name" type="text" class="form-control">
                    </td>
                    <td class="col-md-1">
                        <input id="id_product_category" maxlength="50" name="product_category" type="text" class="form-control">
                    </td>
                    <td class="col-md-2">
                        <input id="id_product_made" maxlength="20" name="product_made" type="text" class="form-control">
                    </td>
                    <td class="col-md-1">
                        <input id="id_product_cost" name="product_cost" min="0" type="number" class="number form-control">
                    </td>
                    <td class="col-md-1">
                        <input id="id_product_count" name="product_count" min="0" type="number" class="number form-control">
                    </td>
                    <td class="col-md-1">
                        <button type="submit" onclick="return check()" onfocus="this.blur()" class="btn btn-success btn-block">Добавить</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

VStorage/templates/VStorage/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load future %}
<head>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>Склад</title>
    <meta charset="utf-8">
</head>
<body>
    <div class="container-fluid">
        <div class="row" id="header_row">
            <div class="col-md-12">
                <header id="header">
                    <div class="col-md-3">
                        <p class="text-center" id="top_text"><big><i>Интернет-магазин электроники</i></big></p>
                    </div>
                    {% if user.is_authenticated %}
                    <div class="col-md-2 col-md-offset-3" id="branch_address">
                    <p class="text-center" id="top_text"><big><i>Филиал №: {{request.session.branch_id}}, {{request.session.branch_address}}</i></big></p>
                    </div>
                    <div class="col-md-3" id="user_name">
                    <p class="text-center" id="top_text"><big><i>Пользователь: {{user.first_name}}</i></big></p>
                    </div>
                    <div class="col-md-offset-11" id="last_block">
                        <form method="post" action="{% url 'store:logout' %}" role="form" id="exit_form">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link btn-block">Выйти</button>
                        </form>
                    </div>
                    {% endif %}
                </header>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {%block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>

VStorage/templates/VStorage/basket.html
{% extends 'VStorage/base.html' %} {% block content %} {% if user.is_authenticated %} {% include 'VStorage/check_input_script.html' %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="table-responsive">
            <form method="post">
                {% csrf_token %}
                <table class="table table-bordered">
                    <caption id="caption_table">
                        <h2>Выбранные товары</h2></caption>
                    <thead>
                        <tr>
                            <th>Номер товара</th>
                            <th>Наименование</th>
                            <th>Категория</th>
                            <th>Страна изготовитель</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <!--<th></th>-->
                        </tr>
                    </thead>
                    <tbody>
                        {% for p_result in request.session.basket %}
                        <tr>
                            <td class="col-md-1">{{p_result.0}}</td>
                            <td class="col-md-2">{{p_result.1}}</td>
                            <td class="col-md-1">{{p_result.2}}</td>
                            <td class="col-md-1">{{p_result.3}}</td>
                            <td class="col-md-1">
                                <input value="{{p_result.5}}" min="1" name="product_count_b" type="number" class="form-control number basket">
                            </td>
                            <td class="col-md-1">{{p_result.4}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-2 col-md-offset-1">
        <button type="submit" formaction="{% url 'store:new_order' %}" onfocus="this.blur()" class="btn btn-primary btn btn-block">Назад</button>
    </div>
    <div class="col-md-2 col-md-offset-6">
        <button type="submit" formaction="{% url 'store:next_basket' %}" onfocus="this.blur()" class="btn btn-primary btn btn-block">Далее</button>
    </div>
</div>
</form>
{% endif %} {% endblock %}

VStorage/templates/VStorage/index.html
{% extends 'VStorage/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <form method="post">
            {% csrf_token %}
            <div class="btn-group-vertical col-md-12">
                <button type="submit" formaction="{% url 'store:products' %}" onfocus="this.blur()" class="btn btn-default btn-lg btn-block">Каталог</button>
                <button type="submit" formaction="{% url 'store:add_product' %}" onfocus="this.blur()" class="btn btn-default btn-lg btn-block">Добавить товар</button>
                <button type="submit" formaction="{% url 'store:new_order' %}" onfocus="this.blur()" class="btn btn-default btn-lg btn-block">Оформить заказ</button>
            </div>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

VStorage/templates/VStorage/login.html
{% extends 'VStorage/base.html' %}
{% block content %}
<br><br><br>
<div class="col-md-4 col-md-offset-4">
    <div class="form-group">
        <form method="post" action="{% url 'store:login' %}" role="form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Логин</label>
                <input type="text" class="form-control" id="id_username" name="username" placeholder="Введите логин">
            </div>
            <div class="form-group">
                <label for="id_password">Пароль</label>
                <input type="password" class="form-control" id="id_password" name="password" placeholder="Пароль">
            </div>
            <button type="submit" class="btn btn-success">Войти</button>
        </form>
    </div>
    {%if error%}
    <div class="text-center text-danger">
        {{error}}
    </div>
</div>
{%endif%}
{% endblock %}

VStorage/templates/VStorage/new_order.html
{% extends 'VStorage/base.html' %}
{% block content %}
{% if user.is_authenticated %}
{% if order_products_list%}
{% include 'VStorage/script.html' %}
{% include 'VStorage/verify_button.html' %}
{% load staticfiles %}
{% load filters %}
<div class="col-md-2 col-md-offset-8" id="basket_block">
    <p>
        <h4 id="count">В корзине {{products_count|products_plural}}</h4></p>
</div>
<div class="col-md-1" id="basket_block">
    <a href="{% url 'store:basket' %}"><img src="{% static 'img/basket.png' %}" id="basket" /></a>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="table-responsive">
            <table class="table table-bordered">
                <caption id="caption_table">
                    <h2>Выбор товаров</h2></caption>
                <thead>
                    <tr>
                        <th>Номер товара</th>
                        <th>Наименование</th>
                        <th>Категория</th>
                        <th>Страна изготовитель</th>
                        <th>Остаток на складе</th>
                        <th>Цена</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in order_products_list %}
                    <tr>
                        <td>{{product.product_id}}</td>
                        <td>{{product.product_name}}</td>
                        <td>{{product.product_category}}</td>
                        <td>{{product.product_made}}</td>
                        <td>{{product.product_rest}}</td>
                        <td>{{product.product_cost}}</td>
                        <td>
                            <button type="submit" id="b{{product.product_id}}" onclick="return check_order({{product.product_id}},
                        '{{product.product_name}}','{{product.product_category}}',
                        '{{product.product_made}}', {{product.product_rest}}, {{product.product_cost}})" onfocus="this.blur()" class="btn btn-success btn-block">Добавить</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% for d_b in request.session.basket %}
            <script>disabled_buttons({{d_b.0}})</script>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %} {% endif %} {% endblock %}

VStorage/templates/VStorage/next_basket.html
{% extends 'VStorage/base.html' %} {% block content %} {% if user.is_authenticated %}
<div class="col-md-10 col-md-offset-1">
    <div class="table-responsive">
        <form method="post">
            {% csrf_token %}
            <table class="table table-bordered">
                <caption id="captiontable">
                    <h3>Введите данные клиента</h3></caption>
                <thead>
                    <tr>
                        <th>Имя клиента</th>
                        <th>Паспортные данные</th>
                        <th>Дата рождения</th>
                        <th>Адрес доставки</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="col-md-2">
                            <input id="id_client_name" maxlength="50" name="client_name" type="text" class="form-control">
                        </td>
                        <td class="col-md-1">
                            <input id="id_client_passport" maxlength="11" name="client_passport" type="text" class="form-control" placeholder="XXXX XXXXXX">
                        </td>
                        <td class="col-md-1">
                            <input id="id_client_birthday" name="client_birthday" type="date" class="form-control" placeholder="YYYY-MM-DD">
                        </td>
                        <td class="col-md-2">
                            <input id="id_address" name="address" maxlength="50" type="text" class="form-control">
                        </td>
                        <td class="col-md-1">
                            <button type="submit" formaction="{% url 'store:result' %}" onfocus="this.blur()" class="btn btn-default btn btn-block">Добавить</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>
{% endif %} {% endblock %}

VStorage/templates/VStorage/script.html
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript">

$(document).ready(function() {
    $('input.number').keypress(function(e) {
        var verified = (e.which == 8 || e.which == undefined || e.which == 0) ? null : String.fromCharCode(e.which).match(/[^0-9]/);
        if (verified) {
            e.preventDefault();
        }
    });
});


function check() {
    // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    function clear_data() {
        $('#id_product_name').val('');
        $('#id_product_category').val('');
        $('#id_product_made').val('');
        $('#id_product_cost').val('');
        $('#id_product_count').val('');
    };

    function show_confirm(json_data) {
        var r = confirm("Этот товар найден на складе, изменить информацию о нем?");
        if (r == true) {
            $.ajax({
                type: "POST",
                url: "{% url 'store:ajax_change_product' %}",
                data: JSON.parse(JSON.stringify(json_data)),
                datatype: 'json'
            });
            clear_data();
        } else {}
    };

    $.ajax({
        type: "POST",
        url: "{% url 'store:ajax_add_product' %}",
        data: {
            'product_name': $('#id_product_name').val(),
            'product_category': $('#id_product_category').val(),
            'product_made': $('#id_product_made').val(),
            'product_cost': $('#id_product_cost').val(),
            'product_count': $('#id_product_count').val(),
        },
        success: function(data) {
            if (typeof data != 'string') {
                show_confirm(data);
            } else {

                if (data != '') {
                    alert(data);
                    clear_data();
                } else {
                    alert("Не все поля формы заполнены");
                }
            }
        },
        datatype: 'json'

    });
    //return false;
};

function basket_count(id, data) {
    var count=data.length;
    var text;

    if (count < 10 || count >= 20) {
        if (count % 10 == 2 || count % 10 == 3 || count % 10 ==4){
            text="В корзине "+data.length+" товара";
        }
        else if (count % 10 == 1) {
            text="В корзине "+data.length+" товар";
        }
        else {
            text="В корзине "+data.length+" товаров";
        }
    }
    else {
        text="В корзине "+data.length+" товаров";
    }

    $('#count').text(text);
    $('#b'+id).prop('disabled', true);
    $('#b'+id).text("В корзине");
    $('#b'+id).css("background-color", "SlateGray");
    $('#b'+id).css("border-color", "SlateGray");
}

function check_order(pr_id, pr_name, pr_categ, pr_made, pr_rest, pr_cost) {
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $.ajax({
        type: "POST",
        url: "{% url 'store:ajax_add_basket' %}",
        data: {
            'product_id': pr_id,
            'product_name': pr_name,
            'product_category': pr_categ,
            'product_made': pr_made,
            'product_cost': pr_cost,
            'product_count': pr_rest,
        },
        success: function(data) {
           basket_count(pr_id, data);
        }
    });
}

</script>